# Generated by Django 4.2.4 on 2023-08-16 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('growweb', '0002_growconfig_soildata_growconfighistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VG', 'Vegetative'), ('FL', 'Flowering')], max_length=2)),
                ('lightOn', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lightOff', models.DecimalField(decimal_places=2, max_digits=4)),
                ('phMin', models.DecimalField(decimal_places=2, max_digits=4)),
                ('phMax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tempMin', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tempMax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('soilHumMin', models.DecimalField(decimal_places=2, max_digits=4)),
                ('soilHumMax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('airHumMin', models.DecimalField(decimal_places=2, max_digits=4)),
                ('airHumMax', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='growconfig',
            name='stage',
        ),
        migrations.AddField(
            model_name='growconfig',
            name='stageType',
            field=models.CharField(choices=[('VG', 'Vegetative'), ('FL', 'Flowering')], default='VG', max_length=2),
        ),
        migrations.AddField(
            model_name='growconfighistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='growconfighistory',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
