# Generated by Django 4.2.4 on 2023-08-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_growconfig_lastupdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growconfig',
            name='stageType',
            field=models.CharField(choices=[('VG', 'Vegetative'), ('FL', 'Flowering'), ('PH', 'Pre-harvest')], default='VG', max_length=2),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('VG', 'Vegetative'), ('FL', 'Flowering'), ('PH', 'Pre-harvest')], max_length=2),
        ),
    ]
